/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GraphWay API
 * API для работы с режимами сессий
 * OpenAPI spec version: 1.0
 */

export interface CreateGraphSessionRequestDTO {
  /** Unique identifier for the session */
  id: string;
  image: Buffer;
  /** Identifier for the data structure type */
  sessionDataStructureId: string;
  /** Identifier for the structure type of data structure */
  sessionStructureId: string;
  /** Identifier for the user */
  userId: string;
  /** Identifier for the session mode */
  sessionModeId: string;
  /** Identifier for the analytics */
  analyticsId: string;
  /** Identifier for the algorithm */
  sessionAlgorithmId: string;
  /** Array of session vertex IDs */
  vertexIds: number[];
  /** Array of session edge IDs */
  edgeIds: number[];
}
