/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GraphWay API
 * API для работы с режимами сессий
 * OpenAPI spec version: 1.0
 */

export interface CreateSessionAlgorithmRequestDTO {
  /** @minLength 2 */
  title: string;
  description: string;
  /** Image file for the session algorithm */
  image: Blob;
  sessionStructureIds: string[];
}
