/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GraphWay API
 * API для работы с режимами сессий
 * OpenAPI spec version: 1.0
 */
import type { SessionDataStructureDTO } from './sessionDataStructureDTO';

export interface FindSessionDataStructuresResponseDTO {
  /** List of session data structures */
  sessionDataStructures: SessionDataStructureDTO[];
}
