/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GraphWay API
 * API для работы с режимами сессий
 * OpenAPI spec version: 1.0
 */
import type { SessionStructureDTO } from './sessionStructureDTO';

export interface FindSessionStructuresResponseDTO {
  /** List of session modes */
  sessionStructures: SessionStructureDTO[];
}
