/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GraphWay API
 * API для работы с режимами сессий
 * OpenAPI spec version: 1.0
 */
import type { SessionAlgorithmDTO } from './sessionAlgorithmDTO';

export interface FindSessionAlgorithmsResponseDTO {
  /** List of session algorithms */
  sessionAlgorithms: SessionAlgorithmDTO[];
}
