/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GraphWay API
 * API для работы с режимами сессий
 * OpenAPI spec version: 1.0
 */

export interface SessionModeDTO {
  /** The unique identifier of the session mode */
  id: string;
  /** The title of the session mode */
  title: string;
  /** The description of the session mode */
  description: string;
  /** The image associated with the session mode */
  image: Blob;
}
