/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GraphWay API
 * API для работы с режимами сессий
 * OpenAPI spec version: 1.0
 */

export interface SessionStructureDTO {
  /** The unique identifier of the session structure */
  id: string;
  /** The title of the session structure */
  title: string;
  /** The description of the session structure */
  description: string;
  /** The image associated with the session structure */
  image: Blob;
  /** The unique identifiers of the session Data Structures that are associated with the session Structure */
  sessionDataStructureIds: string[];
}
