/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GraphWay API
 * API для работы с режимами сессий
 * OpenAPI spec version: 1.0
 */

export interface SessionAlgorithmDTO {
  /** The unique identifier of the session Algorithm */
  id: string;
  /** The title of the session mode */
  title: string;
  /** The description of the session Algorithm */
  description: string;
  /** The image associated with the session Algorithm */
  image: Blob;
  /** The unique identifiers of the session structures that are associated with the session Algorithm */
  sessionStructureIds: string[];
}
