import { customInstance } from '.././customInstance';
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GraphWay API
 * API для работы с режимами сессий
 * OpenAPI spec version: 1.0
 */
import type { CreateGraphSessionRequestDTO } from '.././model';

/**
 * @summary Create a graph session
 */
export type graphSessionControllerCreateGraphSessionResponse = {
  data: void | void;
  status: number;
  headers: Headers;
};

export const getGraphSessionControllerCreateGraphSessionUrl = () => {
  return `/graph-sessions/create`;
};

export const graphSessionControllerCreateGraphSession = async (
  createGraphSessionRequestDTO: CreateGraphSessionRequestDTO,
  options?: RequestInit,
): Promise<graphSessionControllerCreateGraphSessionResponse> => {
  return customInstance<graphSessionControllerCreateGraphSessionResponse>(
    getGraphSessionControllerCreateGraphSessionUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createGraphSessionRequestDTO),
    },
  );
};
