/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GraphWay API
 * API для работы с режимами сессий
 * OpenAPI spec version: 1.0
 */
import { customInstance } from '.././customInstance';

export type appControllerGetHelloResponse = {
  data: void;
  status: number;
  headers: Headers;
}

export const getAppControllerGetHelloUrl = () => {


  return `/`
}

export const appControllerGetHello = async ( options?: RequestInit): Promise<appControllerGetHelloResponse> => {
  
  return customInstance<appControllerGetHelloResponse>(getAppControllerGetHelloUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


